export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_INIT_ERROR = 'AUTH_INIT_ERROR';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const MAIL_INIT = 'MAIL_INIT';
export const MAIL_INIT_ERROR = 'MAIL_INIT_ERROR';

export const PROGRESS_ACTIVATE = 'PROGRESS_ACTIVATE';
export const PROGRESS_INCREMENT = 'PROGRESS_INCREMENT';
export const PROGRESS_DEACTIVATE = 'PROGRESS_DEACTIVATE';